name = "go"
type = "javascript"
account_id = "ad787241fe351c137db64a138baea218"
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [
  { binding = "LINKS", id = "a2466e7c12c44b8ba0638bb3f3d558a1", preview_id = "a2466e7c12c44b8ba0638bb3f3d558a1" }
]
